-- =====================================================================
-- 028 — Importa os projetos da ATA DE REUNIÃO "Projetos x Customer Service"
-- de 29/09/2026 (63 projetos) como processos. Rodar DEPOIS do 001–027.
-- Pode rodar mais de uma vez (não duplica: cada item tem uma referência ata-2026-09-29-NN).
--
-- Como cada item vira processo:
--   • Cliente: pelo CNPJ ou nome já cadastrado (os do Monday); senão cria.
--   • Etapa atual: "Projeto" (inclui sourcing, referências, pesquisa, estimativa em
--     montagem, frete) ou "Apresentação da estimativa" (estimativa já entregue,
--     "após estimativa", novo formulário, reunião de estimativa).
--     Pausados ficam com status Pausado, em Projeto.
--   • Datas: início e prazo da ata (sem data → o campo fica vazio / hoje).
--   • Responsável da etapa: quem tem a tabela na ata (Alycia, Ana Clara, Gabriella,
--     Giovanna, Rodrigo).
--   • Próximo passo da ata vira a "situação" da etapa; status e pendência vão para
--     o histórico do processo.
-- Para desfazer só esta importação:
--   delete from public.processos where monday_id like 'ata-2026-09-29-%';
-- =====================================================================

create or replace function public.importar_ata(p_itens jsonb)
returns int language plpgsql security definer set search_path = public as $$
declare
  it jsonb; n int := 0;
  v_cli uuid; v_id uuid;
  v_ini date; v_fim date; v_hoje date := public.hoje_br(); v_conc date;
  v_proj int; v_apres int; v_alvo int;
  v_resp uuid[];
  v_nome1 text;
begin
  perform set_config('pc.rpc', 'on', true);

  for it in select * from jsonb_array_elements(p_itens) loop
    if exists (select 1 from public.processos where monday_id = it->>'ref') then continue; end if;

    v_ini := coalesce(nullif(it->>'inicio', '')::date, v_hoje);
    v_fim := nullif(it->>'prazo', '')::date;

    -- cliente: CNPJ, senão nome; cria se não existir
    v_cli := null;
    if nullif(it->>'cnpj', '') is not null then
      select id into v_cli from public.clientes where cnpj = it->>'cnpj' limit 1;
    end if;
    if v_cli is null then
      select id into v_cli from public.clientes where lower(trim(nome)) = lower(trim(it->>'empresa')) limit 1;
    end if;
    if v_cli is null then
      insert into public.clientes (nome, cnpj, contato)
      values (trim(it->>'empresa'), nullif(it->>'cnpj', ''), nullif(it->>'contato', ''))
      returning id into v_cli;
    else
      update public.clientes set cnpj = coalesce(cnpj, nullif(it->>'cnpj', '')), contato = coalesce(contato, nullif(it->>'contato', ''))
       where id = v_cli;
    end if;

    v_id := public.criar_processo(null, nullif(it->>'plano', ''), nullif(it->>'produto', ''), false, v_cli);
    update public.processos
       set monday_id = it->>'ref', contato = nullif(it->>'contato', ''),
           created_at = v_ini::timestamp at time zone 'America/Sao_Paulo'
     where id = v_id;

    select min(ordem) filter (where nome = 'Projeto (Flex / Premium / Full)'),
           min(ordem) filter (where nome = 'Apresentação da estimativa')
      into v_proj, v_apres
      from public.processo_etapas where processo_id = v_id;
    v_alvo := case when it->>'destino' = 'apresentacao' then v_apres else v_proj end;

    -- responsável: perfil da equipe cujo nome começa com o primeiro nome da ata (o de nome mais curto)
    v_nome1 := public.pc_normaliza(split_part(trim(it->>'responsavel'), ' ', 1));
    select coalesce(array_agg(x.id), '{}') into v_resp from (
      select p.id from public.profiles p
       where p.tipo = 'equipe' and public.pc_normaliza(coalesce(p.nome, '')) like v_nome1 || '%'
       order by length(p.nome), p.nome limit 1) x;
    update public.processo_etapas
       set responsaveis = case when array_length(v_resp, 1) > 0 then v_resp else responsaveis end,
           responsaveis_label = it->>'responsavel'
     where processo_id = v_id and ordem = v_proj;

    -- etapas antes do alvo: concluídas
    v_conc := least(coalesce(v_fim, v_hoje), v_hoje);
    update public.processo_etapas pe
       set status = 'concluida',
           iniciado_em = v_ini::timestamp at time zone 'America/Sao_Paulo' + interval '9 hours',
           concluido_em = (case when pe.ordem < v_proj then v_ini else greatest(v_conc, v_ini) end)::timestamp at time zone 'America/Sao_Paulo' + interval '18 hours',
           prazo_em = null
     where pe.processo_id = v_id and pe.ordem < v_alvo;

    -- etapa atual
    update public.processo_etapas pe
       set status = 'em_andamento',
           iniciado_em = (case when v_alvo = v_proj then v_ini else greatest(v_conc, v_ini) end)::timestamp at time zone 'America/Sao_Paulo' + interval '9 hours',
           prazo_em = v_fim,
           concluido_em = null,
           situacao = left(nullif(trim(it->>'proximo'), ''), 500)
     where pe.processo_id = v_id and pe.ordem = v_alvo;
    update public.processo_etapas set status = 'pendente', iniciado_em = null, prazo_em = null, concluido_em = null
     where processo_id = v_id and ordem > v_alvo;

    -- checklist das etapas concluídas marcado
    update public.processo_checklist c set feito = true, feito_em = pe.concluido_em
      from public.processo_etapas pe
     where c.processo_etapa_id = pe.id and pe.processo_id = v_id and pe.status = 'concluida' and not c.feito;

    update public.processos set status = case when it->>'grupo' = 'pausado' then 'pausado' else 'ativo' end
     where id = v_id;

    update public.processo_eventos set created_at = v_ini::timestamp at time zone 'America/Sao_Paulo' + interval '9 hours'
     where processo_id = v_id and tipo = 'criado';
    insert into public.processo_eventos (processo_id, tipo, texto)
    values (v_id, 'importado',
      'Importado da ata de 29/09/2026 (Projetos x Customer Service)'
      || E'\nResponsável na ata: ' || (it->>'responsavel')
      || E'\nCliente na ata: ' || (it->>'cliente_ata')
      || E'\nEtapa na ata: ' || coalesce(nullif(it->>'etapa_ata', ''), '—')
      || E'\nStatus: ' || coalesce(nullif(it->>'status_ata', ''), '—')
      || coalesce(E'\nPendência / situação: ' || nullif(it->>'pendencia', ''), '')
      || coalesce(E'\nPróximo passo: ' || nullif(it->>'proximo', ''), ''));
    n := n + 1;
  end loop;

  perform set_config('pc.rpc', 'off', true);
  return n;
end $$;
revoke all on function public.importar_ata(jsonb) from public, anon, authenticated;

select public.importar_ata($ata$[
{"ref": "ata-2026-09-29-01", "responsavel": "Alycia", "empresa": "J L SILVA CONFECÇÕES", "cnpj": "", "contato": "James", "plano": "", "produto": "", "inicio": "2025-07-23", "prazo": "2025-08-26", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando retorno da NTL", "status_ata": "⚪Dependência externa", "pendencia": "Retorno da NLT enviado dia 29/09/2026", "proximo": "Falar para ele sobre a compra da amostra, que seria o caminho mais certeiro.", "cliente_ata": "JAMES – J L SILVA CONFECÇÕES"},
{"ref": "ata-2026-09-29-02", "responsavel": "Alycia", "empresa": "GASNOW INTELIGENCIA DIGITAL LTDA", "cnpj": "64.486.034/0001-10", "contato": "Álvaro", "plano": "", "produto": "Balança para monitorar o peso do gás", "inicio": "2026-04-13", "prazo": "2026-04-24", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando NTL", "status_ata": "⚪Dependência externa", "pendencia": "Reunião com o fornecedor realizada dia 28/09", "proximo": "Aguardando retorno da reunião para passar ao cliente", "cliente_ata": "ÁLVARO – GASNOW INTELIGÊNCIA DIGITAL LTDA – ME"},
{"ref": "ata-2026-09-29-03", "responsavel": "Alycia", "empresa": "WSM IMPORT EXPORT CONSULTING LTDA", "cnpj": "41.865.179/0001-27", "contato": "William", "plano": "Full", "produto": "Acessórios de moto, bicicleta de equilíbrio e máscaras LED", "inicio": "2026-05-07", "prazo": "2026-05-07", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Internacional / fornecedor", "status_ata": "🟡 Em andamento", "pendencia": "Solicitação 1 (Bicicletas): 1000 e 5000 unidades Solicitação 3 (Baú): 1000 unidade e 5000 unidades de plástico e alumínio Solicitação 2 (finamento de impressoras 3D): Cancelado;Solicitação 4 (Limpadores): retorno enviado para os fornecedores, recebemos dia 22/09/2026.", "proximo": "Entrega de nova estimativa de custos, báu e bicicletas.Cobrar os fornecedores de limpadores", "cliente_ata": "WILLIAM – WSM IMPORT EXPORT CONSULTING LTDA"},
{"ref": "ata-2026-09-29-04", "responsavel": "Alycia", "empresa": "DRI FOLHEADOS E ACESSORIOS", "cnpj": "48.392.117/0001-94", "contato": "Adriana", "plano": "Premium", "produto": "Semi-joias", "inicio": "2026-05-25", "prazo": "2026-08-27", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Estimativa de custos", "status_ata": "🟡 Em andamento", "pendencia": "Estimativa de custos entregue, dia 21/09/2026, ultima estimativa de custos entregue", "proximo": "Cliente não deu retorno, chamamos dias 18 e 22 de setembro", "cliente_ata": "ADRIANA – DRI FOLHEADOS E ACESSÓRIOS"},
{"ref": "ata-2026-09-29-05", "responsavel": "Alycia", "empresa": "PRIME COMERCIO, INDUSTRIA E IMPORTACAO LTDA", "cnpj": "38.280.716/0001-62", "contato": "Renato", "plano": "", "produto": "Produtos diversos", "inicio": "2026-06-05", "prazo": "2026-06-19", "destino": "projeto", "grupo": "pausado", "etapa_ata": "Pausado", "status_ata": "⚪ Pausado", "pendencia": "Projeto pausado.", "proximo": "Aguardar definição para retomada.", "cliente_ata": "RENATO – PRIME COMERCIO, INDUSTRIA E IMPORTACAO LTDA"},
{"ref": "ata-2026-09-29-06", "responsavel": "Alycia", "empresa": "TRANSBEM INDUSTRIA E COMERCIO DE PECAS PARA VEICULOS LTDA", "cnpj": "11.487.007/0001-04", "contato": "LUCIANO", "plano": "Full", "produto": "Cinta amarrar carga, farol, presilha e lanterna", "inicio": "2026-06-09", "prazo": "2026-06-21", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa de custos entregue", "status_ata": "🟢 Concluído / acompanhamento", "pendencia": "Estimativa entregue em 09/09/2026; confirmação de informações realizada em 11/09/2026.", "proximo": "Estimativa de custos apresentado dia 22/09, mas foi apresentado como par, mas não era. Apresentar uma estimativa de custos com uma maior quantidade 1000 e 5000, para conseguir o valor unitário menor. Larissa ficou de verificar um frete rodoviário mais barato com o Kledson.", "cliente_ata": "LUCIANO – TRANSBEM INDUSTRIA E COMERCIO DE PECAS PARA VEICULOS"},
{"ref": "ata-2026-09-29-07", "responsavel": "Alycia", "empresa": "AGROPECUARIA INOVACAO LTDA", "cnpj": "32..411.713/0001-34", "contato": "Fernando", "plano": "Full", "produto": "Pneu", "inicio": "2026-03-17", "prazo": "2026-04-27", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🔴 Atenção", "pendencia": "Aguardando retorno do cliente. Último contato em 24/09/2026.", "proximo": "Marcar uma reunião de alimento com o cliente, para escolher dos itens.", "cliente_ata": "FERNANDO – AGROPECUÁRIA INOVAÇÃO LTDA & JULIANO – CEREALISTA HEINRICH"},
{"ref": "ata-2026-09-29-08", "responsavel": "Alycia", "empresa": "JARDIX COMERCIO DE PECAS E ACESSORIOS LTDA", "cnpj": "40.691.322/0001-49", "contato": "Vanessa", "plano": "Full", "produto": "vela de ignição, carburador, embreagem, conjunto de combustível, carretel de nylon, acelerador completo, tanque de combustível, porca lamina, filtro de combustível, carretel manual.", "inicio": "2026-06-30", "prazo": "2026-07-27", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🔴 Atenção", "pendencia": "Aguardando retorno sobre os produtos. Último contato em 02/09/2026.", "proximo": "Marcar de alimento marcada para o dia 01/10/2026", "cliente_ata": "VANESSA – JARDIX COMERCIO DE PECAS E ACESSORIOS LTDA – ME"},
{"ref": "ata-2026-09-29-09", "responsavel": "Alycia", "empresa": "ELPLAY MOBILIDADE LTDA", "cnpj": "23.610.374/0001-24", "contato": "Sergio", "plano": "", "produto": "electric mountain bike", "inicio": "2026-07-28", "prazo": "2026-08-14", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Após estimativa", "status_ata": "🟡 Aguardando retorno", "pendencia": "Estimativa apresentada em 09/09/2026; aguardando retorno do cliente.", "proximo": "Cliente não compareceu a reunião de apresentação dia 24/09/2026", "cliente_ata": "SÉRGIO – ELPLAY MOBILIDADE LTDA"},
{"ref": "ata-2026-09-29-10", "responsavel": "Alycia", "empresa": "TRATORUNO PECAS E SERVICOS PARA TRATORES LTDA", "cnpj": "02.819.698/0001-05", "contato": "Bruno", "plano": "Full", "produto": "Chapa de aço", "inicio": "2026-07-30", "prazo": "2026-08-30", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Frete internacional", "status_ata": "🔴 Atenção", "pendencia": "Aguardando retorno do frete internacional desde 28/08/2026.", "proximo": "Marta cobrou a Isabelle, porque o cliente está no frete internacional desde o dia 02/09/2026", "cliente_ata": "BRUNO – TRATORUNO PECAS E SERVICOS PARA TRATORES LTDA"},
{"ref": "ata-2026-09-29-11", "responsavel": "Alycia", "empresa": "WALKRUNNER FITNESS LTDA", "cnpj": "67.517.564/0001-77", "contato": "Leonildo Alves de Lima", "plano": "", "produto": "Academia", "inicio": "2026-08-07", "prazo": "2026-08-28", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa entregue", "status_ata": "🟢 Finalizado", "pendencia": "Estimativa de custos entregue em 24/08/2026 às 09h51.", "proximo": "Acompanhar devolutiva/continuidade.", "cliente_ata": "LEONILDO – WALKRUNNER FITNESS LTDA – Ana Paula"},
{"ref": "ata-2026-09-29-12", "responsavel": "Alycia", "empresa": "MAXFIX COMERCIO DE FITAS ADESIVAS LTDA", "cnpj": "10.908.041/0001-34", "contato": "Marcos", "plano": "", "produto": "Acrílico", "inicio": "2026-08-13", "prazo": "2026-08-28", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa entregue", "status_ata": "🟢 Fechamento", "pendencia": "Estimativa entregue em 19/08/2026 às 14h22.", "proximo": "Acompanhar devolutiva/continuidade.", "cliente_ata": "MARCOS – MAXFIX COMERCIO DE FITAS ADESIVAS LTDA. – Fernanda"},
{"ref": "ata-2026-09-29-13", "responsavel": "Alycia", "empresa": "AIRMAQ COMERCIAL IMPORTADORA E EXPORTADORA LTDA", "cnpj": "23.250.563/0001-33", "contato": "Rafael", "plano": "", "produto": "Compressor de ar", "inicio": "2026-08-14", "prazo": "2026-09-02", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Busca de fornecedor / retorno cliente", "status_ata": "🔴 Projeto solicitado e finalizado", "pendencia": "Estimativa entregue em 18/08/2026. Cliente ficou de verificar a válvula. Serão verificados outros fornecedores na Canton Fair. Aguardando retorno desde 24/08/2026.", "proximo": "Verificar fornecedores na Canton Fair e acompanhar cliente.", "cliente_ata": "RAFAEL – AIRMAQ COMERCIAL IMPORTADORA E EXPORTADORA LTDA."},
{"ref": "ata-2026-09-29-14", "responsavel": "Alycia", "empresa": "MARIN BRASIL TURBONET LTDA", "cnpj": "24.839.614/0001-20", "contato": "Fabiano", "plano": "", "produto": "Motos elétricas", "inicio": "2026-04-30", "prazo": "2026-05-15", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa entregue", "status_ata": "🔴 Finalizado", "pendencia": "Estimativa entregue, cliente não responde. Último contato em 24/08/2026.", "proximo": "Cliente não deu retorno", "cliente_ata": "FABIANO – MARIN BRAISL TURBONET LTDA"},
{"ref": "ata-2026-09-29-15", "responsavel": "Alycia", "empresa": "DIAMOND CAR ELETRICOS LTDA", "cnpj": "44.989.477/0001-17", "contato": "Thalita", "plano": "Premium", "produto": "carrinho elétrico para criança", "inicio": "2026-08-20", "prazo": "2026-10-05", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa / verificação", "status_ata": "🟡 Em andamento", "pendencia": "Informações enviadas para a NTL", "proximo": "Cobrando a NTL, para termos uma devolutiva da cotação.", "cliente_ata": "THALITA – DIAMOND CAR ELETRICOS LTDA"},
{"ref": "ata-2026-09-29-16", "responsavel": "Alycia", "empresa": "SAFE BRASIL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA", "cnpj": "18.074.238/0001-27", "contato": "André", "plano": "Full", "produto": "Motor e mecanismo que reduz velocidade", "inicio": "2026-09-01", "prazo": "2026-09-30", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing", "status_ata": "🟡 Em andamento", "pendencia": "Busca de fornecedores.", "proximo": "Cliente não passou especificação técnica dos produtos, só fotos com uma péssima qualidade dos itens. Vamos enviar os catálogos para o cliente definir o produto.", "cliente_ata": "ANDRÉ – SAFE BRASIL COMERCIO E LOCACAO DE EQUIPAMENTOS LTDA"},
{"ref": "ata-2026-09-29-17", "responsavel": "Alycia", "empresa": "APPARATUS BRASIL INDUSTRIA IMPORTACAO EXPORTACAO E COMERCIO DE EQUIPAMENTOS ESPORTIVOS LTDA", "cnpj": "45.894.140/0001-99", "contato": "Luciano", "plano": "", "produto": "Equipamento de ginastica", "inicio": "2026-09-01", "prazo": "2026-09-23", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa / apresentação", "status_ata": "🟡 Próximo do prazo", "pendencia": "Estimativa entregue em 14/09/2026. Apresentação marcada para 18/09/2026.", "proximo": "Segunda solicitação de estimativa de custos, recebemos o frete internacional, seguimos para a montagem de estimativa de custos, e entrega.", "cliente_ata": "LUCIANO – APPARATUS BRASIL INDUSTRIA IMPORTACAO EXPORTACAO E COMERCIO DE EQUIPAMENTOS ESPORTIVOS LTDA"},
{"ref": "ata-2026-09-29-18", "responsavel": "Alycia", "empresa": "SOLICITAÇÃO DE PESQUISA - CANTON FAIR - PESQUISA HOSPITALAR - ALEXANDRE E CARLA", "cnpj": "", "contato": "", "plano": "", "produto": "SOLICITAÇÃO DE PESQUISA", "inicio": "2026-09-01", "prazo": "2026-09-30", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa", "status_ata": "🟡Pesquisa finalizada", "pendencia": "Informações sobre produtos enviadas por e-mail em 14/09/2026. Imersão será verificada com Olacyr.", "proximo": "Perguntas sobre os produtos enviadas para os fornecedores na quinta, aguardando retorno deles.", "cliente_ata": "ALEXANDRE E CARLA – PESQUISA HOSPITALAR / CANTON FAIR"},
{"ref": "ata-2026-09-29-19", "responsavel": "Alycia", "empresa": "TIINK COSMETICOS LTDA", "cnpj": "35.612.594/0001-76", "contato": "Camila Oliveira Marcelino", "plano": "Full", "produto": "produtos de beleza", "inicio": "2026-09-02", "prazo": "2026-10-01", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa e desenvolvimento", "status_ata": "🟡 Em andamento", "pendencia": "Passar o retorno da reunião para os fornecedores.E pesquisa de novos produtos.", "proximo": "Preparar novas cotações.", "cliente_ata": "CAMILA OLIVEIRA MARCELINO – TIINK COSMETICOS LTDA"},
{"ref": "ata-2026-09-29-20", "responsavel": "Alycia", "empresa": "ASSOCIACAO DA GINASTICA DE TRAMPOLIM DE CONTAGEM", "cnpj": "32.026.741/0001-38", "contato": "Luciano", "plano": "", "produto": "TELA DE SALTO PARA TRAMPOLIN", "inicio": "2026-09-01", "prazo": "2026-09-23", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Frete internacional", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de apresentação de estimativa de custos", "proximo": "Entrega de estimativa de custos", "cliente_ata": "LUCIANO – ASSOCIACAO DA GINASTICA DE TRAMPOLIM DE CONTAGEM"},
{"ref": "ata-2026-09-29-21", "responsavel": "Alycia", "empresa": "GL INFO SOM LTDA", "cnpj": "13.687.627/0001-04", "contato": "Gustavo", "plano": "", "produto": "iluminação", "inicio": null, "prazo": "2026-09-24", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing", "status_ata": "🟡 Em andamento", "pendencia": "Esperando o cliente pagar o restante do sourcing", "proximo": "Cotação de frete internacional.", "cliente_ata": "GUSTAVO – GL INFO SOM LTDA"},
{"ref": "ata-2026-09-29-22", "responsavel": "Alycia", "empresa": "MAGAZINE CAMARGOS VALLE LTDA", "cnpj": "37.281.514/0001-72", "contato": "Bruno", "plano": "", "produto": "Panela", "inicio": null, "prazo": "2026-09-23", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Estimativa de custos", "status_ata": "🟡 Em andamento", "pendencia": "Solicitada nova estimativa do 1º fornecedor e nova estimativa do 2º fornecedor.", "proximo": "Montagem de estimativa de custos", "cliente_ata": "BRUNO – MAGAZINE CAMARGOS VALLE LTDA"},
{"ref": "ata-2026-09-29-23", "responsavel": "Alycia", "empresa": "K. FERREIRA COMERCIO E SERVICO DE MAQUINAS E EQUIPAMENTOS LTDA", "cnpj": "31.392.907/0001-77", "contato": "KAIO ALEXANDRE FERREIRA", "plano": "", "produto": "Furo serrilhado de dois lados com duas bordas Faca", "inicio": "2026-09-16", "prazo": "2026-09-30", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Estimativa de custos", "status_ata": "🟡 Em andamento", "pendencia": "Estimativa de custos entregues dia 25/09/2026 (ultimo estimativa entregue nessa data)", "proximo": "", "cliente_ata": "K. FERREIRA COMERCIO E SERVICO DE MAQUINAS E EQUIPAMENTOS LTDA (31.392.907/0001-77) KAIO ALEXANDRE FERREIRA"},
{"ref": "ata-2026-09-29-24", "responsavel": "Alycia", "empresa": "ALTA CONQUISTA SOLUCOES AQUATICAS", "cnpj": "05.314.730/0001-80", "contato": "Renato", "plano": "Premium", "produto": "Diversos", "inicio": "2026-09-25", "prazo": "2026-10-08", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Estimativa de custos", "status_ata": "", "pendencia": "Cotação de frete internacional", "proximo": "", "cliente_ata": "Renato, Alta conquista"},
{"ref": "ata-2026-09-29-25", "responsavel": "Ana Clara", "empresa": "LIVA SERVICES LTDA", "cnpj": "63.943.092/0001-63", "contato": "RENATO", "plano": "Flex", "produto": "Baterias", "inicio": "2026-01-01", "prazo": "2026-02-10", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing / aguardando cliente", "status_ata": "🔴 Atenção", "pendencia": "Estimativa entregue e apresentada em 18/08/2026. Cliente informou que avaliaria viabilidade e interesse em semijoias. Demanda enviada ao Sourcing de Semijoias em 19/08/2026; sem retorno até a data da ata.", "proximo": "Tentamos contato dia 02/09/2026, sem retorno.", "cliente_ata": "RENATO – LIVA SERVICES LTDA"},
{"ref": "ata-2026-09-29-26", "responsavel": "Ana Clara", "empresa": "J.J ELETRICIDADE IMPORTS LTDA", "cnpj": "65.354.116/0001-74", "contato": "Guilherme", "plano": "Premium", "produto": "Luminárias: Arandelas, luminárias pendentes, plafons, spots, lâmpadas led, pista de dança 4x4/ 2X. Fones; Interruptor; Alexia; Projetor;", "inicio": "2026-04-10", "prazo": "2026-06-11", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🟡 próximo do prazo", "pendencia": "Cliente dará retorno sobre novo formulário. Sem retorno desde 12/08/2026.", "proximo": "Cliente vai trocar de seguimentos.Vou enviar um sourcing que já tenho de telas led e os catálogos para o cliente avaliar.", "cliente_ata": "GUILHERME – J. J. ELETRICIDADE IMPORTS LTDA"},
{"ref": "ata-2026-09-29-27", "responsavel": "Ana Clara", "empresa": "ROBSON LUIZ MICHELETTO", "cnpj": "53.416.494/0001-56", "contato": "Robson", "plano": "Full", "produto": "Máquina de cortar grama", "inicio": "2026-04-13", "prazo": "2026-05-22", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Após estimativa", "status_ata": "🔴 Atenção", "pendencia": "Nova estimativa entregue e apresentada em 17/08/2026. Cliente informou que não gostou de alguns valores.", "proximo": "06/07/ Cliente não deu mais retorno.", "cliente_ata": "ROBSON LUIZ MICHELETTO"},
{"ref": "ata-2026-09-29-28", "responsavel": "Ana Clara", "empresa": "IMPERIO DAS REDES LTDA", "cnpj": "65.887.673/0001-50", "contato": "Eduardo Martins", "plano": "Full", "produto": "Fio em multifilamento polipropileno", "inicio": "2026-06-16", "prazo": "2026-06-28", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Novo formulário", "status_ata": "🟡 Aguardando cliente", "pendencia": "Estimativa entregue; produto não apresentou preço devido à matéria-prima. Cliente enviará novo formulário.", "proximo": "Cliente ainda não deu retorno com relação ao formulário de novo produto.", "cliente_ata": "EDUARDO MARTINS – IMPERIO DAS REDES LTDA"},
{"ref": "ata-2026-09-29-29", "responsavel": "Gabriella", "empresa": "AGÊNCIA BOLD MKT", "cnpj": "", "contato": "Luis", "plano": "", "produto": "", "inicio": "2025-12-16", "prazo": "2026-01-30", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🟡 Aguardando cliente", "pendencia": "Aguardando retorno sobre a nova escolha.", "proximo": "Rodrigo está em contato com o cliente.", "cliente_ata": "LUIS – AGÊNCIA BOLD MKT"},
{"ref": "ata-2026-09-29-30", "responsavel": "Gabriella", "empresa": "RAPPI 10 RAPIDEZ E CONFIANCA", "cnpj": "26.454.968/0001-81", "contato": "Li Santos", "plano": "Full", "produto": "Materiais de construção", "inicio": "2025-12-02", "prazo": "2026-02-25", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa", "status_ata": "🟡 Em análise", "pendencia": "Estimativa atualizada; valor do frete internacional não permite chamar o cliente no momento.", "proximo": "Avaliar viabilidade e acompanhar frete.", "cliente_ata": "LI SANTOS – RAPPI 10 RAPIDEZ E CONFIANÇA"},
{"ref": "ata-2026-09-29-31", "responsavel": "Gabriella", "empresa": "ROYAL ATACADISTA LTDA", "cnpj": "39.678.603/0001-82", "contato": "Victor", "plano": "Full", "produto": "Portas", "inicio": "2026-03-28", "prazo": "2026-05-11", "destino": "projeto", "grupo": "pausado", "etapa_ata": "Pausado", "status_ata": "⚪ Pausado", "pendencia": "Projeto pausado visando redução do frete internacional.", "proximo": "Acompanhar possibilidade de redução do frete.", "cliente_ata": "VICTOR – ROYAL ATACADISTA LTDA"},
{"ref": "ata-2026-09-29-32", "responsavel": "Gabriella", "empresa": "LYRA COMERCIO E SERVICOS DE MATERIAIS ELETRICOS, ELETRONICOS E FERRAMENTAS LTDA", "cnpj": "42.679.362/0001-09", "contato": "Marivania", "plano": "Full", "produto": "Headset, fones, câmeras e carregadores", "inicio": "2026-04-02", "prazo": "2026-05-14", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Amostra", "status_ata": "🟡 Em andamento", "pendencia": "Pagamento de amostra realizado.Enviamos o código de rastreio.", "proximo": "Montagem de estimativa de custos, e agora vamos apresentar para a cliente semana que vem.", "cliente_ata": "MARIVANIA – LYRA COMÉRCIO E SERVIÇOS DE MATERIAIS ELÉTRICOS, ELETRONICOS E FERRAMENTAS LTDA"},
{"ref": "ata-2026-09-29-33", "responsavel": "Gabriella", "empresa": "IMEX 360 COMERCIO EXTERIOR LTDA", "cnpj": "11.101.705/0001-11", "contato": "Alexandre", "plano": "Full", "produto": "Luva", "inicio": "2026-04-15", "prazo": "2026-05-28", "destino": "projeto", "grupo": "pausado", "etapa_ata": "Pausado", "status_ata": "⚪ Pausado", "pendencia": "Projeto pausado.", "proximo": "Aguardar definição para retomada.", "cliente_ata": "ALEXANDRE – IMEX 360 COMÉRCIO EXTERIOR LTDA"},
{"ref": "ata-2026-09-29-34", "responsavel": "Gabriella", "empresa": "GMS COMERCIO DE MOTOS E ACESSORIOS LTDA", "cnpj": "63.240.217/0001-99", "contato": "Gustavo Machado", "plano": "Full", "produto": "Carregador para bicicleta, motor scooter moto, Pneu bike e scooter, pedais, triciclo, patinete, painel digital, bicicleta elétrica e ergométrica", "inicio": "2026-06-08", "prazo": "2026-07-20", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Apresentação de estimativa", "status_ata": "🟡 Em andamento", "pendencia": "Foram feitas 9 estimativas. Última entregue em 02/09/2026 às 10h04. Paula irá apresentar.", "proximo": "Ana Paula está tentando realizar o processo de apresentação de estimativa, mas o cliente não do retorno.", "cliente_ata": "GUSTAVO – GMS COMERCIO DE MOTOS E ACESSORIOS LTDA. – Paula"},
{"ref": "ata-2026-09-29-35", "responsavel": "Gabriella", "empresa": "MARRARA PECCININ DESPACHANTE LTDA", "cnpj": "", "contato": "Marcello", "plano": "", "produto": "", "inicio": null, "prazo": null, "destino": "projeto", "grupo": "pausado", "etapa_ata": "Pausado", "status_ata": "⚪ Pausado", "pendencia": "Projeto pausado.", "proximo": "Aguardar definição para retomada.", "cliente_ata": "MARCELLO – MARRARA PECCININ DESPACHANTE LTDA"},
{"ref": "ata-2026-09-29-36", "responsavel": "Gabriella", "empresa": "SETE INDUSTRIA E COMERCIO LTDA", "cnpj": "48.135.251/0001-00", "contato": "Fabio", "plano": "Premium", "produto": "QUIMICOS E ADITIVOS RELACIONADOS", "inicio": "2026-05-19", "prazo": "2026-06-02", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Documentação", "status_ata": "⚪Dependência externa", "pendencia": "Aguardando a NTL enviar a cotação da amostra química.Enviamos as 4 estimativas de custos de embalagens.", "proximo": "Cliente precisa dar uma devolutiva das questões envidas, para a entrega da estimativa de custos dos produtos químicos. Solicitar para o contador do cliente que analise o ICMS dos produtos. Entregar a estimativa de custos dos químicos", "cliente_ata": "FABIO – SETE INDUSTRIA COMÉRCIO LTDA"},
{"ref": "ata-2026-09-29-37", "responsavel": "Gabriella", "empresa": "ON LED ILUMINACAO E MATERIAIS ELETRICOS LTDA", "cnpj": "17.146.063/0001-53", "contato": "THIAGO", "plano": "Flex", "produto": "Fitas LED", "inicio": "2026-02-20", "prazo": "2026-02-26", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Reunião de estimativa", "status_ata": "🔴 Atenção", "pendencia": "Estimativa entregue em 13/08/2026 às 10h14. Último contato em 19/08/2026. Reunião ainda em alinhamento.", "proximo": "Cliente não deu retorno para agendamento da reunião de estimativa, 18/08/2026", "cliente_ata": "THIAGO – ON LED ILUMINAÇÃO E MATERIAIS ELÉTRICOS LTDA"},
{"ref": "ata-2026-09-29-38", "responsavel": "Gabriella", "empresa": "IPBF COMERCIO LTDA", "cnpj": "61.733.855/0001-16", "contato": "Isabela e Patrícia", "plano": "Premium", "produto": "Abridor de Latas Elétrico Recarregável", "inicio": "2026-07-15", "prazo": "2026-08-08", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Novo formulário", "status_ata": "🟡 Finalizado", "pendencia": "Estimativa entregue em 01/09/2026 às 17h56. Cliente não gostou dos valores por conta da certificação e enviará novo formulário.", "proximo": "Cliente optou por não realizar o processo por conta da cerificação necessária para importar os itens, e decidiu começar um sourcing de outro segmento.", "cliente_ata": "ISABELA E PATRICIA – IPBF COMERCIO LTDA"},
{"ref": "ata-2026-09-29-39", "responsavel": "Gabriella", "empresa": "PORTAS CAPIXABA LTDA", "cnpj": "09.449.880/0001-52", "contato": "Cristiano de Sales Roldi", "plano": "Full", "produto": "Porta com montante em madeira", "inicio": "2026-07-17", "prazo": "2026-08-28", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Novo formulário", "status_ata": "🟡 Aguardando cliente", "pendencia": "Reunião de estimativa realizada em 02/09/2026. Estimativa entregue em 25/08/2026 às 16h31. Cliente enviará novo formulário.", "proximo": "Cliente ficou de fazer um novo formulário 22/09/2026. Se até semana que vem o cliente não der retorno com relação ao novo formulário, vamos pesquisar fornecedores de garrafas de vídeos, para montra um drive com os catálogos e mandar para o cliente.", "cliente_ata": "CRISTIANO DE SALES ROLDI – PORTAS CAPIXABA LTDA"},
{"ref": "ata-2026-09-29-40", "responsavel": "Gabriella", "empresa": "KAWA7 COMERCIO VREJISTA DE MATERIAIS ELETRICOS HIDRAULICOS FERRAGENS E FERRAMENTAS LTDA", "cnpj": "53.998.583/0001-58", "contato": "Cristiano", "plano": "Premium", "produto": "Peças hidráulicas", "inicio": "2026-08-12", "prazo": "2026-09-09", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing", "status_ata": "⚪Dependência externa", "pendencia": "Verificação de estimativa de custos.", "proximo": "Apresentar a estimativa de custos semana que vem.", "cliente_ata": "CRISTIANO – KAWA7 COMERCIO VAREJISTA DE MATERIAIS ELETRICOS HIDRAULICOS FERRAGENS E FERRAMENTAS LTDA"},
{"ref": "ata-2026-09-29-41", "responsavel": "Gabriella", "empresa": "FAMILIA BILINGUE IDIOMAS LTDA", "cnpj": "37.837.735/0001-84", "contato": "Abdaliana", "plano": "Full", "produto": "Livros", "inicio": "2026-08-14", "prazo": "2026-09-24", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🟡 Aguardando cliente", "pendencia": "Aguardando retorno da cliente.Aguardando retorno da NTL para a cotação das amostras.", "proximo": "Cliente tem que passar o retorno sobre qual fornecedores devemos seguir.Enviar a estimativa de custos de amostra para o cliente.", "cliente_ata": "ABDALIANA – FAMILIA BILINGUE IDIOMAS LTDA."},
{"ref": "ata-2026-09-29-42", "responsavel": "Gabriella", "empresa": "STOFF-CAR BANCOS PARA VANS LTDA", "cnpj": "47.431.596/0001-48", "contato": "Jomar Souza Santos", "plano": "Premium", "produto": "Máquina e bancos", "inicio": "2026-09-01", "prazo": "2026-10-15", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa e desenvolvimento", "status_ata": "🟡 Em andamento", "pendencia": "Montagem do sourcing. Estamos alinhando alguns detalhes com os fornecedores das maquinas, sobre especificações técnicas solicitadas pelo cliente.", "proximo": "Explicar para o cliente que já estamos com todos os fornecedores, e já iniciamos a montagem da apresentação. Porém estamos alinhando com os fornecedores das máquinas alguns detalhes para passar para ele verificar se a máquinas está de acordo com o que ele precisa, com isso semana que vem conseguimos dar um parecer sobre o agendamento da reunião de apresentação de sourcing.", "cliente_ata": "JOMAR SOUZA SANTOS – STOFF-CAR BANCOS PARA VANS LTDA"},
{"ref": "ata-2026-09-29-43", "responsavel": "Gabriella", "empresa": "BRUNO RAFAEL GRISOTTO", "cnpj": "31.542.063/0001-01", "contato": "Cesar", "plano": "Full", "produto": "chapas de vidro", "inicio": "2026-09-01", "prazo": "2026-10-01", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa e desenvolvimento", "status_ata": "🟡 Em andamento", "pendencia": "Apresentação de sourcing realizada 30/09/2026. Cliente gostou do fornecedor 1° Larissa ficou de passar para ele o sourcing e as planilhas de apoio pelo WhatsApp. Cliente ficou de selecionar os produtos e quantidade de containers que vai querer de cada um, para montarmos a estimativa de custos. Temos que habilitar o radar do cliente, para entender o quanto ele pode importar.", "proximo": "Cliente tem que passar a documentação para a habilitação de radar. Mandar os itens que vão para a estimativa de custos.", "cliente_ata": "CESAR – BRUNO RAFAEL GRISOTTO"},
{"ref": "ata-2026-09-29-44", "responsavel": "Gabriella", "empresa": "DIAS & PARIZOTTO MULTIMARCAS LTDA", "cnpj": "42.514.980/0001-90", "contato": "Ivanir A. D. Parizotto", "plano": "Premium", "produto": "Utensílios domésticos", "inicio": "2026-09-01", "prazo": "2026-10-15", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing / apresentação", "status_ata": "🟡 próximo do prazo", "pendencia": "Produtos de cada, solicitação de frete internacional. Sourcing de cortinas, lençol, toalha, jogo de cama, recebendo cotação dos fornecedores. Xicaras, tachas, recebendo cotação dos fornecedores. Ar-condicionado, recebendo cotação dos fornecedores.", "proximo": "Finalizar apresentação e realizar reunião.", "cliente_ata": "IVANIR A. D. PARIZOTTO – DIAS & PARIZOTTO MULTIMARCAS LTDA"},
{"ref": "ata-2026-09-29-45", "responsavel": "Gabriella", "empresa": "Ronney e Fabricio (sem empresa)", "cnpj": "", "contato": "Ronney e Fabricio", "plano": "", "produto": "", "inicio": "2026-09-11", "prazo": "2026-10-26", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Referências", "status_ata": "🟡 Em andamento", "pendencia": "Finalizando a pesquisa. Analisando cotações e fornecedores.", "proximo": "Estamos analisando o perfil dos fornecedores, para montar a apresentação de sourcing e seguir para que ela aconteça.", "cliente_ata": "RONNEY E FABRICIO – SEM EMPRESA"},
{"ref": "ata-2026-09-29-46", "responsavel": "Gabriella", "empresa": "MAURO PEREIRA DOS REIS", "cnpj": "05.293.905/0001-10", "contato": "Moacir e Guilherme", "plano": "Premium", "produto": "Fone de ouvido, parafusadeira, patinete e roda", "inicio": "2026-09-17", "prazo": "2026-10-28", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Referências", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de referência.", "proximo": "Finalizando a pesquisa. Analisando cotações e fornecedores.", "cliente_ata": "Moacir e Guilherme - MAURO PEREIRA DOS REIS"},
{"ref": "ata-2026-09-29-47", "responsavel": "Gabriella", "empresa": "CASA DO MOTOQUEIRO DISTRIBUIDORA LTDA", "cnpj": "", "contato": "Hugo e Lorena", "plano": "", "produto": "", "inicio": null, "prazo": "2026-10-23", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Referências", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de referência.", "proximo": "Finalizando a pesquisa. Analisando cotações e fornecedores.", "cliente_ata": "Hugo e Lorena - CASA DO MOTOQUEIRO DISTRIBUIDORA LTDA"},
{"ref": "ata-2026-09-29-48", "responsavel": "Giovanna", "empresa": "G D RUFINO LTDA", "cnpj": "00.425.586/0001-36", "contato": "Jesse", "plano": "Full", "produto": "Parafuso, Arruela, Porca, Chave combinada, Barras de Fibra de Carbono", "inicio": "2026-06-13", "prazo": "2026-10-19", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Estimativa de amostras", "status_ata": "🟡 Em andamento", "pendencia": "1º fornecedor: solicitação de estimativa de amostra. 2º fornecedor: aguardando documentação para solicitar estimativa de amostra.", "proximo": "Cotando amostras.", "cliente_ata": "JESSE – G D RUFINO LTDA"},
{"ref": "ata-2026-09-29-49", "responsavel": "Giovanna", "empresa": "ELYON DELIVERY IMPORTS & MARKETING - LTDA", "cnpj": "56.422.757/0001-28", "contato": "Diego Cruz", "plano": "Full", "produto": "Refletor, Plafon, Parafusa eira", "inicio": "2026-07-13", "prazo": "2026-10-19", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Cotações", "status_ata": "🟡 Em andamento", "pendencia": "Estimativa de custos", "proximo": "Analisando certificação do INMETRO", "cliente_ata": "DIEGO CRUZ – ELYON DELIVERY IMPORTS & MARKETING – LTDA"},
{"ref": "ata-2026-09-29-50", "responsavel": "Giovanna", "empresa": "GIGA BIKE MOBILIDADE LTDA", "cnpj": "66.326.467/0001-34", "contato": "Marlon Vicentini", "plano": "Full", "produto": "motos elétricas", "inicio": "2026-07-15", "prazo": "2026-10-25", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Apresentação de estimativa", "status_ata": "🟡 Aguardando apresentação", "pendencia": "Estimativa entregue em 02/09/2026. Fernanda irá apresentar.", "proximo": "Cotação estava muito fora.", "cliente_ata": "MARLON VICENTINI – GIGA BIKE MOBILIDADE LTDA"},
{"ref": "ata-2026-09-29-51", "responsavel": "Giovanna", "empresa": "MATHEUS RODRIGUES VERAS", "cnpj": "41.346.526/0001-05", "contato": "Matheus", "plano": "Premium", "produto": "HD, Alicate, escova sanitária, faca tática e ferro de solda", "inicio": "2026-07-17", "prazo": "2026-09-19", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Apresentação de Sourcing", "status_ata": "🟡 próximo do prazo", "pendencia": "Cotação de 10000 e 5000 peças já temos de um fornecedor, estamos desenvolvendo um segundo fornecedor/", "proximo": "Vamos montar uma apresentação com esse fornecedor que já temos e vamos mandar no grupo, explicando que esse fornecedor do sourcing anterior e aumento o valor, com isso estamos desenvolvendo outros.", "cliente_ata": "MATHEUS – MATHEUS RODRIGUES VERAS"},
{"ref": "ata-2026-09-29-52", "responsavel": "Giovanna", "empresa": "SABRIMAR MATERIAIS DE CONSTRUCAO LTDA", "cnpj": "05.886.568/0001-75", "contato": "Marcio", "plano": "Full", "produto": "Hikvision NVR, CCTV, Switch Hikvision, HIKVISION HUB", "inicio": "2026-07-28", "prazo": "2026-09-07", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🔴 Atenção", "pendencia": "Reunião de Sourcing realizada em 24/08/2026. Cliente informou que os valores são semelhantes aos que já compra no Paraguai. Aguardando retorno.", "proximo": "Cliente não da devolutiva, só passou que os valores estão fora, então mandamos para a NTL para tentarmos um valor melhor.", "cliente_ata": "MARCIO – SABRIMAR MATERIAIS DE CONSTRUCAO LTDA"},
{"ref": "ata-2026-09-29-53", "responsavel": "Giovanna", "empresa": "CARBUS PECAS E ACESSORIOS LTDA", "cnpj": "05.060.510/0001-78", "contato": "Robson Silva", "plano": "Premium", "produto": "Piso vinílico, autopeças e chapa de alumínio", "inicio": null, "prazo": "2026-09-18", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Apresentação de Sourcing", "status_ata": "🟡 próximo do prazo", "pendencia": "Cotando a quantidade maior.", "proximo": "Vamos apresentar um sourcing com maior quantidade. Para tentar conseguir um melhor valor.", "cliente_ata": "ROBSON – CARBUS PECAS E ACESSORIOS LTDA"},
{"ref": "ata-2026-09-29-54", "responsavel": "Giovanna", "empresa": "WEVOLTS IMPORTACAO E COMERCIO LTDA", "cnpj": "67.112.674/0001-59", "contato": "Leandro", "plano": "Full", "produto": "Moto Elétrica", "inicio": "2026-08-06", "prazo": "2026-09-15", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Aguardando cliente", "status_ata": "🔴 Finalizado", "pendencia": "Estimativa entregue em 28/08/2026 às 17h45. Apresentação realizada em 31/08/2026. Aguardando retorno.", "proximo": "O valor de sourcing foi finalizado", "cliente_ata": "LEANDRO – WEVOLTS IMPORTACAO E COMERCIO LTDA"},
{"ref": "ata-2026-09-29-55", "responsavel": "Giovanna", "empresa": "UNI3 SOLUCOES PROMOCIONAIS IMPORTADORA E EXPORTADORA LTDA", "cnpj": "65.768.388/0001-10", "contato": "Mauricio", "plano": "Full", "produto": "Marca texto, garrafa e caneca", "inicio": "2026-08-12", "prazo": "2026-09-22", "destino": "apresentacao", "grupo": "ativo", "etapa_ata": "Estimativa / frete", "status_ata": "🟡 Em andamento", "pendencia": "Fernanda vai apresentar a estimativa de custos", "proximo": "Ver se o cliente vai fechar", "cliente_ata": "MAURÍCIO – UNI3 SOLUCOES PROMOCIONAIS IMPORTADORA E EXPORTADORA LTDA – Fernanda e Ana Clara"},
{"ref": "ata-2026-09-29-56", "responsavel": "Giovanna", "empresa": "M & F MÁQUINAS E FERRAMENTAS", "cnpj": "23.875.559/0001-60", "contato": "Felipe", "plano": "Premium", "produto": "partes e peças", "inicio": "2026-09-01", "prazo": "2026-10-12", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Apresentação de Sourcing", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de apresentação de Sourcing.", "proximo": "Finalizar apresentação.", "cliente_ata": "FELIPE – M & F MÁQUINAS E FERRAMENTAS"},
{"ref": "ata-2026-09-29-57", "responsavel": "Giovanna", "empresa": "OTZ GESTAO EMPRESARIAL LTDA", "cnpj": "37.241.683/0001-89", "contato": "Tigmos", "plano": "Full", "produto": "Motos elétricas", "inicio": "2026-09-01", "prazo": "2026-10-01", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Sourcing", "status_ata": "⚪Dependência externa", "pendencia": "Solicitação PI e PL", "proximo": "Solicitação de cotação de frete", "cliente_ata": "TIGMOS – OTZ GESTAO EMPRESARIAL LTDA"},
{"ref": "ata-2026-09-29-58", "responsavel": "Giovanna", "empresa": "Alfredo e Laertes (sem empresa)", "cnpj": "", "contato": "Alfredo e Laertes", "plano": "Premium", "produto": "PET, Utensílios, Organização de Cozinha, Decoração e Organização da Casa", "inicio": "2026-09-14", "prazo": "2026-10-28", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Referências", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de sourcing", "proximo": "Realizar reunião semana que vem de apresentação de sourcing", "cliente_ata": "ALFREDO E LAERTES – SEM EMPRESA"},
{"ref": "ata-2026-09-29-59", "responsavel": "Giovanna", "empresa": "ALBERICI PELLETS LTDA", "cnpj": "01.130.505/0001-33", "contato": "Fabio", "plano": "Premium", "produto": "Chapas", "inicio": "2026-09-11", "prazo": "2026-10-26", "destino": "projeto", "grupo": "ativo", "etapa_ata": "", "status_ata": "🟡 Em andamento", "pendencia": "Alinhamento de PI e PL de todos os fornecedores, montagem de sourcing", "proximo": "", "cliente_ata": "Fabio, ALBERICI PELLETS LTDA"},
{"ref": "ata-2026-09-29-60", "responsavel": "Giovanna", "empresa": "PRISMA SOLUCOES LTDA", "cnpj": "68.532.880/0001-80", "contato": "Roni", "plano": "", "produto": "", "inicio": null, "prazo": "2026-10-23", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Referências", "status_ata": "🟡 Em andamento", "pendencia": "Montagem de referências.", "proximo": "Finalizar referências.", "cliente_ata": "PRISMA SOLUCOES LTDA (68.532.880.0001-80) Roni"},
{"ref": "ata-2026-09-29-61", "responsavel": "Rodrigo", "empresa": "AMOCHUVA COMERCIO DE ARTIGOS DO VESTUARIO E ACESSORIOS LTDA", "cnpj": "57.961.069/0001-07", "contato": "Carina", "plano": "Full", "produto": "Fone de ouvido, parafusadeira, patinete e roda", "inicio": "2026-09-22", "prazo": "2026-10-21", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa", "status_ata": "🟡 Em andamento", "pendencia": "1º fornecedor: solicitação de estimativa de amostra. 2º fornecedor: aguardando documentação para solicitar estimativa de amostra.", "proximo": "Acompanhar documentação e estimativas.", "cliente_ata": "CARINA- AMOCHUVA COMERCIO DE ARTIGOS DO VESTUARIO E ACESSORIOS LTDA"},
{"ref": "ata-2026-09-29-62", "responsavel": "Rodrigo", "empresa": "ROYAL ELETRIC MOTORS ASSESSORIA EM IMPORTACAO E EXPORTACAO LTDA", "cnpj": "37.683.876/0001-90", "contato": "Leonardo", "plano": "Full", "produto": "Produtos de academia", "inicio": "2026-09-23", "prazo": "2026-10-22", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa", "status_ata": "🟡 Em andamento", "pendencia": "Alinhamento das cotações recebidas.", "proximo": "Concluir alinhamento das cotações.", "cliente_ata": "LEONARDO - ROYAL ELETRIC MOTORS ASSESSORIA EM IMPORTACAO E EXPORTACAO LTDA"},
{"ref": "ata-2026-09-29-63", "responsavel": "Rodrigo", "empresa": "FERNANDO (empresa não informada)", "cnpj": "", "contato": "Fernando", "plano": "", "produto": "", "inicio": "2026-09-23", "prazo": "2026-10-22", "destino": "projeto", "grupo": "ativo", "etapa_ata": "Pesquisa", "status_ata": "🟡 Em andamento", "pendencia": "Alinhamento das cotações recebidas.", "proximo": "Concluir alinhamento das cotações.", "cliente_ata": "Fernando"}
]$ata$::jsonb) as processos_importados;

notify pgrst, 'reload schema';
